import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./shared/Navbar";
import Footer from "./shared/Footer";
import Banner from "./components/Banner";
import { ToastContainer } from "react-toastify";
import { MyProvider } from "./context/MyContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MyProvider>
          <Navbar />
          {children}
          <ToastContainer />
          <Footer />
        </MyProvider>
      </body>
    </html>
  );
}
